# Install Python
- name: Install dnf packages
  ansible.builtin.dnf:
    # Ansible automatically loops if given a vector variable
    # as a parameter to most tasks
    name: "{{ packages }}"
  # need to be root to install stuff
  become: true
  # define variables here
  vars:
    # these are essential python stuff you need to download first
    # any other dependencies must be declared in requirements.txt
    packages:
    - python
    - python-pip
