- name: Generate Keys Locally
  hosts: localhost
  roles:
    - role: 02_create_keys
      vars:
        ansible_host_key_checking: false

- name: Send keys to Nodes
  hosts: client, cluster
  roles:
    - role: 03_install_keys
      vars:
        ansible_host_key_checking: false
